[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "marketing-multi-agent-system"
version = "0.1.0"

[tool.setuptools]
package-dir = {"" = "src"}
packages = {find = {where = ["src"]}}